// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tenminutes;

import com.tenminutes.Timer;

privileged aspect Timer_Roo_JavaBean {
    
    public String Timer.getMessage() {
        return this.message;
    }
    
    public void Timer.setMessage(String message) {
        this.message = message;
    }
    
}
